### PR TITLE
Added place data for wards, polling stations and booths.

### PR DESCRIPTION
**Pull request by raghavio**
Missing booths are stored with name 'Unknown'

```
AC0020173
AC0600094
AC0410076
AC0340316
AC0020071
AC0610028
AC0640178
AC0340369
AC0580049
AC0610096
AC0340079
AC0020022
AC0580050
AC0650052
AC0250024
AC0570131
AC0420121
AC0380017
AC0230076
AC0380041
AC0620030
AC0400009
AC0690138
AC0420001
AC0060229
AC0400142
AC0380109
AC0500146
AC0050205
AC0420105
AC0640143
AC0420005
AC0420091
AC0380105
AC0380113
AC0180070
AC0600018
AC0420092
AC0570132
AC0240126
AC0250129
AC0400036
AC0510037
AC0400055
AC0640063
AC0680005
AC0420104
AC0640179
AC0510001
AC0610024
AC0060228
AC0220091
AC0200056
AC0620031
AC0330078
AC0380108
```

### CODE REVIEW

**Comment by anandology** [comment]
@RaghavPro have you also included the missing booths in this PR? If not, could you please included them with name as "Name Unknown" or something?

Please change the name of 4-lb.txt to 4-ward.txt.

**Comment by raghavio** [comment]
Sure. Give me a minute.

**Comment by raghavio** [comment]
Done. Forced pushed into 1 commit.

**Comment by anandology** [comment]
Does it include all the booths now?

**Comment by raghavio** [comment]
Yes.

Date: Wed, 2 Mar 2016 03:33:50 -0800

**Pull request merged**
